spring.application.name=StudentMysql

spring.datasource.username=root
spring.datasource.password=password

spring.datasource.url=jdbc:mysql://localhost:3306/springapp1
spring.jpa.hibernate.ddl-auto=update